### ISSUE TITLE
Week 1 Question

### ISSUE THREAD

**Issue by awheels-ds** [maustin-resultant/professional-development#1]
1. Using Python, write a program that prints the numbers ranging from one to 50. But for multiples of three, print "Fizz" instead of the number, and for the multiples of five, print "Buzz." For numbers which are multiples of both three and five, print "FizzBuzz".

**Comment by maustin-resultant** [comment]
Week 1 Question 1 Code:

`for num in range(1,51):
    if num % 3 is 0 and num % 5 is 0:
        print("FizzBuzz")
    elif num % 3 is 0:
        print("Fizz")
    elif num % 5 is 0:
        print("Buzz")
    else:
        print(num)`
